// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WalletExplorerLazyImport = createFileRoute('/wallet-explorer')()
const TokenExplorerLazyImport = createFileRoute('/token-explorer')()
const LeaderboardLazyImport = createFileRoute('/leaderboard')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WalletExplorerLazyRoute = WalletExplorerLazyImport.update({
  path: '/wallet-explorer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/wallet-explorer.lazy').then((d) => d.Route),
)

const TokenExplorerLazyRoute = TokenExplorerLazyImport.update({
  path: '/token-explorer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/token-explorer.lazy').then((d) => d.Route),
)

const LeaderboardLazyRoute = LeaderboardLazyImport.update({
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/leaderboard.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      preLoaderRoute: typeof LeaderboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/token-explorer': {
      preLoaderRoute: typeof TokenExplorerLazyImport
      parentRoute: typeof rootRoute
    }
    '/wallet-explorer': {
      preLoaderRoute: typeof WalletExplorerLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LeaderboardLazyRoute,
  TokenExplorerLazyRoute,
  WalletExplorerLazyRoute,
])
