/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SwapImport } from './routes/swap'
import { Route as SubcriptionsImport } from './routes/subcriptions'
import { Route as MyPortfolioImport } from './routes/my-portfolio'
import { Route as MarketImport } from './routes/market'
import { Route as EducationImport } from './routes/education'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as BotsStrategyImport } from './routes/bots-strategy'
import { Route as IndexImport } from './routes/index'
import { Route as OnchainDiscoveryWalletExplorerImport } from './routes/onchain-discovery/wallet-explorer'
import { Route as OnchainDiscoveryTokenExplorerImport } from './routes/onchain-discovery/token-explorer'
import { Route as OnchainDiscoveryOnchainSignalsImport } from './routes/onchain-discovery/onchain-signals'
import { Route as OnchainDiscoveryLeaderboardImport } from './routes/onchain-discovery/leaderboard'
import { Route as AcademyCoursesImport } from './routes/academy/courses'
import { Route as AcademyArticlesImport } from './routes/academy/articles'
import { Route as OnchainDiscoveryWalletExplorerGroupIdDeepImport } from './routes/onchain-discovery/wallet-explorer_.$groupId.deep'
import { Route as OnchainDiscoveryTokenExplorerTokenDeepImport } from './routes/onchain-discovery/token-explorer_.$token.deep'
import { Route as AcademyCoursesCourseIdDeepImport } from './routes/academy/courses_.$courseId.deep'
import { Route as AcademyArticlesArticleIdDeepImport } from './routes/academy/articles_.$articleId.deep'

// Create Virtual Routes

const TradingTerminalLazyImport = createFileRoute('/trading-terminal')()

// Create/Update Routes

const TradingTerminalLazyRoute = TradingTerminalLazyImport.update({
  path: '/trading-terminal',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/trading-terminal.lazy').then((d) => d.Route),
)

const SwapRoute = SwapImport.update({
  path: '/swap',
  getParentRoute: () => rootRoute,
} as any)

const SubcriptionsRoute = SubcriptionsImport.update({
  path: '/subcriptions',
  getParentRoute: () => rootRoute,
} as any)

const MyPortfolioRoute = MyPortfolioImport.update({
  path: '/my-portfolio',
  getParentRoute: () => rootRoute,
} as any)

const MarketRoute = MarketImport.update({
  path: '/market',
  getParentRoute: () => rootRoute,
} as any)

const EducationRoute = EducationImport.update({
  path: '/education',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BotsStrategyRoute = BotsStrategyImport.update({
  path: '/bots-strategy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnchainDiscoveryWalletExplorerRoute =
  OnchainDiscoveryWalletExplorerImport.update({
    path: '/onchain-discovery/wallet-explorer',
    getParentRoute: () => rootRoute,
  } as any)

const OnchainDiscoveryTokenExplorerRoute =
  OnchainDiscoveryTokenExplorerImport.update({
    path: '/onchain-discovery/token-explorer',
    getParentRoute: () => rootRoute,
  } as any)

const OnchainDiscoveryOnchainSignalsRoute =
  OnchainDiscoveryOnchainSignalsImport.update({
    path: '/onchain-discovery/onchain-signals',
    getParentRoute: () => rootRoute,
  } as any)

const OnchainDiscoveryLeaderboardRoute =
  OnchainDiscoveryLeaderboardImport.update({
    path: '/onchain-discovery/leaderboard',
    getParentRoute: () => rootRoute,
  } as any)

const AcademyCoursesRoute = AcademyCoursesImport.update({
  path: '/academy/courses',
  getParentRoute: () => rootRoute,
} as any)

const AcademyArticlesRoute = AcademyArticlesImport.update({
  path: '/academy/articles',
  getParentRoute: () => rootRoute,
} as any)

const OnchainDiscoveryWalletExplorerGroupIdDeepRoute =
  OnchainDiscoveryWalletExplorerGroupIdDeepImport.update({
    path: '/onchain-discovery/wallet-explorer/$groupId/deep',
    getParentRoute: () => rootRoute,
  } as any)

const OnchainDiscoveryTokenExplorerTokenDeepRoute =
  OnchainDiscoveryTokenExplorerTokenDeepImport.update({
    path: '/onchain-discovery/token-explorer/$token/deep',
    getParentRoute: () => rootRoute,
  } as any)

const AcademyCoursesCourseIdDeepRoute = AcademyCoursesCourseIdDeepImport.update(
  {
    path: '/academy/courses/$courseId/deep',
    getParentRoute: () => rootRoute,
  } as any,
)

const AcademyArticlesArticleIdDeepRoute =
  AcademyArticlesArticleIdDeepImport.update({
    path: '/academy/articles/$articleId/deep',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bots-strategy': {
      preLoaderRoute: typeof BotsStrategyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/education': {
      preLoaderRoute: typeof EducationImport
      parentRoute: typeof rootRoute
    }
    '/market': {
      preLoaderRoute: typeof MarketImport
      parentRoute: typeof rootRoute
    }
    '/my-portfolio': {
      preLoaderRoute: typeof MyPortfolioImport
      parentRoute: typeof rootRoute
    }
    '/subcriptions': {
      preLoaderRoute: typeof SubcriptionsImport
      parentRoute: typeof rootRoute
    }
    '/swap': {
      preLoaderRoute: typeof SwapImport
      parentRoute: typeof rootRoute
    }
    '/trading-terminal': {
      preLoaderRoute: typeof TradingTerminalLazyImport
      parentRoute: typeof rootRoute
    }
    '/academy/articles': {
      preLoaderRoute: typeof AcademyArticlesImport
      parentRoute: typeof rootRoute
    }
    '/academy/courses': {
      preLoaderRoute: typeof AcademyCoursesImport
      parentRoute: typeof rootRoute
    }
    '/onchain-discovery/leaderboard': {
      preLoaderRoute: typeof OnchainDiscoveryLeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/onchain-discovery/onchain-signals': {
      preLoaderRoute: typeof OnchainDiscoveryOnchainSignalsImport
      parentRoute: typeof rootRoute
    }
    '/onchain-discovery/token-explorer': {
      preLoaderRoute: typeof OnchainDiscoveryTokenExplorerImport
      parentRoute: typeof rootRoute
    }
    '/onchain-discovery/wallet-explorer': {
      preLoaderRoute: typeof OnchainDiscoveryWalletExplorerImport
      parentRoute: typeof rootRoute
    }
    '/academy/articles/$articleId/deep': {
      preLoaderRoute: typeof AcademyArticlesArticleIdDeepImport
      parentRoute: typeof rootRoute
    }
    '/academy/courses/$courseId/deep': {
      preLoaderRoute: typeof AcademyCoursesCourseIdDeepImport
      parentRoute: typeof rootRoute
    }
    '/onchain-discovery/token-explorer/$token/deep': {
      preLoaderRoute: typeof OnchainDiscoveryTokenExplorerTokenDeepImport
      parentRoute: typeof rootRoute
    }
    '/onchain-discovery/wallet-explorer/$groupId/deep': {
      preLoaderRoute: typeof OnchainDiscoveryWalletExplorerGroupIdDeepImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BotsStrategyRoute,
  DashboardRoute,
  EducationRoute,
  MarketRoute,
  MyPortfolioRoute,
  SubcriptionsRoute,
  SwapRoute,
  TradingTerminalLazyRoute,
  AcademyArticlesRoute,
  AcademyCoursesRoute,
  OnchainDiscoveryLeaderboardRoute,
  OnchainDiscoveryOnchainSignalsRoute,
  OnchainDiscoveryTokenExplorerRoute,
  OnchainDiscoveryWalletExplorerRoute,
  AcademyArticlesArticleIdDeepRoute,
  AcademyCoursesCourseIdDeepRoute,
  OnchainDiscoveryTokenExplorerTokenDeepRoute,
  OnchainDiscoveryWalletExplorerGroupIdDeepRoute,
])

/* prettier-ignore-end */
